### ISSUE TITLE
Light Eater is missing info

### ISSUE THREAD

**Issue by Xayrlen** [nornagon/cdda-guide#110]
Page URL: https://nornagon.github.io/cdda-guide/#/mutation/LIGHTEATER

I have tested it in-game and found out, that Light Eater also conflicts with Fast Metabolism aside from Rapid Metabolism. Probably could add that too in the conflict section next to Rapid Metabolism.

**Comment by nornagon** [comment]
This is because Light Eater and Fast Metabolism share the type `METABOLISM`. You can only have one mutation of a given mutation type at a time, unless you have mutations that depend on each other. Since Light Eater and Fast Metabolism share a type and don't depend on each other, they conflict.

This could be more obvious in the UI, but all the info is there! I think actually the fact that Light Eater explicitly lists Rapid Metabolism as a conflicting mutation is redundant, and even without that it would still conflict.

**Comment by nornagon** [comment]
(for future reference, here's the code in CDDA which implements this logic: https://github.com/CleverRaven/Cataclysm-DDA/blob/5de5b3f73473266b671802b63f8533f489a24494/src/mutation.cpp#L1200-L1205)
