### ISSUE TITLE
Not Updating to latest version

### ISSUE THREAD

**Issue by yoshiquest** [nornagon/cdda-guide#111]
The most recent version of the guide right now is for a build from October 15th, and it hasn't updated since.

Looking through the closed issues, it seems that this also happened a month prior in #108 . It might be the same thing happening again, so it could be a good place to start searching.

**Comment by nopenoperson** [comment]
yeah

**Comment by nornagon** [comment]
This is now fixed.

**Comment by nornagon** [comment]
For a little more context: this issue has been due to disk space issues on GitHub Actions. It turns out GH Actions have a max disk space size of around 50 GB, and https://github.com/nornagon/cdda-data was running up against that limit.

I've now implemented a retention policy which should cap the size of the repository to a more reasonable limit:
- All builds from the last 30 days are kept,
- In the following 60 days, we keep the latest build from every other day,
- In the following 120 days, we keep the latest build from every fourth day,
- In the following 240 days, we keep the latest build from every sixteenth day,
- We always keep non-prerelease (i.e. stable) builds.

Hopefully this should strike a good balance between having current builds and historical builds available.
