### ISSUE TITLE
Practice recipes

### ISSUE THREAD

**Issue by Inglonias** [nornagon/cdda-guide#39]
It may be worth considering adding the practice recipes to the guide. Not the most pressing thing, but worth considering.

**Comment by nornagon** [comment]
Hm, where do you imagine these would go in the guide? They don't produce any items, and currently the only place we display recipes is on the items that are the result of a recipe.

**Comment by Inglonias** [comment]
I uh... I dunno. Sorry. That's a very good point.

**Comment by Maleclypse** [comment]
> Perhaps they could go on the skill page...? e.g. https://nornagon.github.io/cdda-guide/#/skill/mechanics

That would be an excellent place for them I think.

**Comment by coyo7e** [comment]
The practise recipes are also all over the place as-is right now, some of them require a component, some require a physical item nearby (training dummy, plus potentially a weapon etc), and some but not nearly all of them produce waste products which are either useless or very low value.

I would like to be able to look up "Bandaging (beginner)" and know that it takes X amount of band-aids of one flavor or another and that I always poop out a few rags, but a lot of other practise recipes give no output, so those unfinished "pracising" items are just trash I throw into a brazier and hope the game burns them up. No, really, they will never go away otherwise.

**Comment by cosmo-naut** [comment]
Perhaps 'recipes' as a category could have it's own catalog which can be browsed.

**Comment by nornagon** [comment]
This is finally done, they show up on skill pages at https://cdda-guide.nornagon.net/skill/mechanics now :)

(also skills are now searchable!)
