### ISSUE TITLE
Comparison tool

### ISSUE THREAD

**Issue by DoctorGoat** [nornagon/cdda-guide#58]
It'd be nice if you could do, for example, -hhg vs zombie_hulk kevlar_hulk to get a two-paned page similar to the item comparison page ingame, or -hhg vs barrett ruger to get an item comparison between the two. 

Just, each flag that's unique would be green on that side, each number that's bigger would be green on its side and red on the other, etc.

**Comment by nornagon** [comment]
I've thought about compare-mode before, but it's technically quite difficult 😅 it would mean plumbing an optional second set of comparison values everywhere any number or value is shown.

I'll leave this open because it's something I'd like, but I have no plans to work on this in the foreseeable future.

**Comment by nornagon** [comment]
I've thought about this further and I don't think this is something that's feasible in the near term. Especially for layered armor in the current version, doing a sane comparison view would be a huge amount of work.

As such, I'm going to close this issue as not planned. I'm open to revisiting in future if I come up with any bright ideas about how this could be implemented.
