### ISSUE TITLE
Obtaining items by clearing rubble

### ISSUE THREAD

**Issue by hexagonrecursion** [nornagon/cdda-guide#59]
You can get wood ash, long sticks and a couple other items by clearing a pile of ash with a shovel, but this is not currently reflected in the "Obtaining" section.

**Comment by nornagon** [comment]
Ehh, this is a bit tricky actually. Clearing rubble doesn't spawn any items, but `f_ash` is a SEALED CONTAINER, and mapgen code (sometimes) spawns ash inside it: https://github.com/CleverRaven/Cataclysm-DDA/blob/cc10e0c20a291462f48e0f9e1a3d82c5e492d166/src/map_extras.cpp#L1981-L1982

Since this is encoded in C++, I don't think there's anything we can really do on the Guide side for now.
