### ISSUE TITLE
Better armor parsing

### ISSUE THREAD

**Issue by Terrorforge** [nornagon/cdda-guide#79]
There have been a number of updates to the armor system that have resulted in the HHG displaying misleading stats. Mostly it seems to be averaging the material coverage. For example, the scrap suit is listed as having 13.00 bash resistance and 95% coverage on the HHG, when in reality it has 75% steel coverage and 25% essentially no armor.

I know solving this isn't trivial, because the new armor definitions are pretty complicated and hard to communicate in a sensible way. But the in-game ui makes a good effort, so maybe you can copy what that's doing?

If you don't have the time or will to work that out right away, maybe it would be prudent to put up a little disclaimer on armor using non-trivial layering (i.e. where covered_by_mat isn't uniform)? "This armor has varying material coverage, and these numbers are averages. Consult the .json for more details" or something like that. I mean I can deal, but I'm concerned that a new player will look up the stats on e.g. the scrap suit and be confused when it doesn't match what's in the game.

**Comment by nornagon** [comment]
Thanks for the report. It took me a while to get to this, but fdfa0a2 should address this. I made the decision to show this slightly differently than how the data appears in-game, because I don't feel like the in-game numbers are very clear. Instead, I show each material layer along with its thickness, coverage and protection values. I thought about additionally showing the best/worst/median values which are the "summary" of all the materials, but I think it would take up too much space, and I'm not sure it adds much (other than a check that the in-game and Guide data are the same).

I'm not super thrilled with the current presentation and I'd like to make it clearer how these values are actually used in-game. But this should at least provide all the available data!

**Comment by Terrorforge** [comment]
> I'm not sure it adds much (other than a check that the in-game and Guide data are the same).

I'm not sure it would even do that. The game also gets very confused by complex examples like Patchwork Armor. It actually displays the "median" value as just being the values for Flesh, despite there only being a 4% chance of hitting only flesh.

Actually, wouldn't the best way to display this data be that graph? I don't know if it would be practical in terms of performance or layout to include in the HHG, but it's certainly the most understandable format I've seen for this system so far.

Anyway, thanks for your excellent work as always.

**Comment by nornagon** [comment]
I'll think about adding the graph to the Guide, it would be a fair bit of work to add but it might be worth it :)
