### ISSUE TITLE
LIGHT_10 LIGHT_300 LIGHT_310 and LIGHT_500 not listed in Catalogs>Flags

### ISSUE THREAD

**Issue by bhauptman-git** [nornagon/cdda-guide#83]
https://nornagon.github.io/cdda-guide/#/json_flag page does not list the LIGHT_10 (oil lamp), LIGHT_300 (flashlight), LIGHT_310 (torch) and LIGHT_500 (heavy-duty flashlight) flags.  There might be others, but I didn't find them.

Useful to find light sources, especially if you need to craft one.

**Comment by nornagon** [comment]
Unfortunately these are "implicit flags" so they're not ever defined anywhere in the JSON. See https://github.com/CleverRaven/Cataclysm-DDA/blob/8157ece0f94417c2454e31dcf80b56be5b417a42/src/item_factory.cpp#L299-L319

Individual LIGHT_* flags work, e.g. https://nornagon.github.io/cdda-guide/#/json_flag/LIGHT_300, because the Guide just searches for all items with that specific string flag.

This is kind of a hack in the game and should probably be restructured in the JSON, but I'm not sure I want to add hacks to the Guide to compensate. I'm going to close this for now, will reopen if I reconsider.
